name: connectivity_plus_linux
description: Linux implementation of the connectivity_plus plugin
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 1.3.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus_platform_interface: ^1.2.0
  meta: ^1.7.0
  nm: 
  git:
    ref: f7508a8936b9e0fd1e8e0604afd4d6b22803bfe1
    url: https://github.com/sikandernoori/nm.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  mockito: ^5.0.0
  flutter_lints: ^1.0.4

flutter:
  plugin:
    implements: connectivity_plus
    platforms:
      linux:
        dartPluginClass: ConnectivityLinux
        pluginClass: none
